---
- name: Update and upgrade Proxmox PVE server
  hosts: proxmox_pve
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages (dist-upgrade)
      apt:
        upgrade: dist

    - name: Install needrestart
      apt:
        name: needrestart
        state: present

    - name: Check if a reboot is required
      command: needrestart -r l
      register: needrestart_output
      failed_when: false
      changed_when: "'REBOOT' in needrestart_output.stdout"

    - name: Reboot the system if required
      reboot:
        msg: "Reboot initiated by Ansible due to updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: "'REBOOT' in needrestart_output.stdout"
