---
- name: Update and upgrade Proxmox PVE server
  hosts: proxmox-pve
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages (dist-upgrade)
      apt:
        upgrade: dist

    - name: Reboot the server if required
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

